(function(){'use strict';var e={};function h(b){var a=/^webkit/;Object.getOwnPropertyNames(b.prototype).forEach(function(c){a.test(c)&&Object.defineProperty(b.prototype,c[6].toLowerCase()+c.slice(7),{get:function(){return this[c]},set:function(a){this[c]=a}})})}
e={s:function(){window.Blob=window.Blob||window.webkitBlob||void 0;window.File=window.File||window.webkitFile||void 0;window.FileReader=window.FileReader||window.webkitFileReader||void 0;return Blob&&File&&FileReader?(h(window.Blob),h(window.File),h(window.FileReader),!0):!1},o:function(){window.DataView=window.DataView||window.webkitDataView||void 0;return DataView?(h(window.DataView),!0):!1}};
if(e.s()&&e.o()){Blob.prototype.a=0;Blob.c=1;Blob.a=2;Blob.b=3;Blob.prototype.j=function(b){this.a+=b;this.a>this.size&&(this.a=this.size)};Blob.prototype.v=function(){this.a=0};Blob.prototype.c=function(){return this.a===this.size};Blob.prototype.b=function(b){return this.slice(this.a,this.a+b)};Blob.prototype.u=function(b){b=this.b(b);this.a+=b.size;return b};var k=function(){this.l=this.m=this.type=null},l=function(){this.b=this.c=this.a=this.i=this.parent=null;this.result=function(){this.c||this.b||
this.a||(this.a=Error("Cannot find codec information"));return{error:this.a,video:this.c&&{codec:this.c.l},audio:this.b&&{codec:this.b.l}}}},n={64:"aac",102:"aac",103:"aac",104:"aac",105:".mp3",107:".mp3",165:"ac-3",169:"dts",221:"vorbis"},p=function(b,a){a=a||0;this.type=b.getUint8(a);this.size=0;this.b=1;this.a=0;for(var c=4;this.b++,c--;){var d=b.getUint8(a+1+(3-c));this.size=this.size<<7|d&127;if(!(d&128))break}},q=function(b,a){a=a||0;p.call(this,b,a);if(3!==this.type)this.a=this.size-this.b;
else{a+=this.b;this.a=3;var c=b.getUint8(a+2);c&128&&(this.a+=2);c&64&&(this.a+=1+b.getUint8(a+this.a));c&32&&(this.a+=2)}},r=function(b,a){a=a||0;p.call(this,b,a);4!==this.type?(this.c=null,this.a=this.size-this.b):(a+=this.b,this.c=b.getUint8(a),this.a=13)},t=function(b,a){a=a||0;this.size=b.getUint32(a,!1);this.type=String.fromCharCode.apply(null,new Uint8Array(b.buffer,a+4,4));this.a=0;this.b=!1},u={},v=function(b,a,c,d,g){a.j(8+b.a);a.c()?d(c):(g=g||new FileReader,g.onloadend=function(f){f.target.readyState===
FileReader.DONE&&(8>f.target.result.byteLength?(c.a=Error("Input data is corrupted or not encoded as mp4/mov"),d(c)):(f=new DataView(f.target.result),f=new t(f,0),8>f.size?(c.a=Error("Input data is corrupted or not encoded as mp4/mov"),d(c)):f.type in u&&u[f.type].h?(c.parent=b.type,u[f.type].h(f,a.u(f.size),c,function(){a.c()?d(c):g.readAsArrayBuffer(a.b(8))})):(a.j(f.size),a.c()?d(c):g.readAsArrayBuffer(a.b(8)))))},g.readAsArrayBuffer(a.b(8)))},w=function(b,a,c,d){if(b.type in u)if(b.b)v(b,a,c,
d);else if(u[b.type].g){var g=new FileReader,f=-1==u[b.type].f?b.size:u[b.type].f;g.onloadend=function(m){m.target.readyState===FileReader.DONE&&(m.target.result.byteLength<f?(c.a=Error("Input data is corrupted or not encoded as mp4/mov"),d(c)):(m=new DataView(m.target.result),b=u[b.type].g(c,m,0),v(b,a,c,d,g)))};g.readAsArrayBuffer(a.b(f))}else b.a=u[b.type].f-8,v(b,a,c,d);else d(c)},x=function(b,a){a=a||0;t.call(this,b,a);var c=String.fromCharCode.apply(null,new Uint8Array(b.buffer,a+12,8));this.j=
c.slice(0,4);this.c=c.slice(4);this.a=this.size-8;this.b=!0},y=function(b,a){a=a||0;t.call(this,b,a);a+=12;this.c=b.getUint32(a,!1);this.j=0<this.c?String.fromCharCode.apply(null,new Uint8Array(b.buffer,a+8,4)):null;this.a=8;this.b=!0},z=function(b,a){a=a||0;t.call(this,b,a);this.a=16;var c=b.getUint16(a+16,!1);this.a=0===c?this.a+12:1===c?this.a+28:2===c?this.a+48:this.size-8;this.b=!0},A=function(b,a){a=a||0;t.call(this,b,a);a+=12;this.a=this.size-8;var c=new q(b,a);a+=c.b+c.a;c=new r(b,a);this.c=
c.c;this.b=!0};u.moov={h:w,f:8,g:void 0};u.trak={h:function(b,a,c,d){c.i=new k;v(b,a,c,function(a){"vide"===a.i.m&&null===a.c?a.c=a.i:"soun"===a.i.m&&null===a.b&&(a.b=a.i);a.i=null;d(a)})},f:8,g:void 0};u.mdia={h:w,f:8,g:void 0};u.hdlr={h:function(b,a,c,d){"mdia"===c.parent?w(b,a,c,d):d(c)},f:20,g:function(b,a,c){a=new x(a,c);b.i.type=a.j;b.i.m=a.c;return a}};u.minf={h:w,f:8,g:void 0};u.stbl={h:w,f:8,g:void 0};u.stsd={h:w,f:24,g:function(b,a,c){a=new y(a,c);0<a.c&&"mp4a"!==a.j&&(b.i.l=a.j,a.a=a.size-
8);return a}};u.mp4a={h:function(b,a,c,d){"stsd"===c.parent?w(b,a,c,d):d(c)},f:18,g:function(b,a,c){return new z(a,c)}};u.wave={h:w,f:8,g:void 0};u.esds={h:w,f:-1,g:function(b,a,c){a=new A(a,c);null!==a.c&&(b.i.l=n[a.c]);return a}};window.MP4={supported:!0,analyze:function(b,a){if(!(b instanceof Blob))throw new TypeError("Invalid argument type");var c=new ArrayBuffer(8),c=new DataView(c),d=new t(c);d.size=8+b.size;d.type="root";d.a=-8;d.b=!0;var g=new FileReader;g.onloadend=function(c){c.target.readyState===
FileReader.DONE&&("ftyp"!=c.target.result?(c=new l,c.a=Error("Input data format is not mp4/mov"),a(c.result())):(b.v(),v(d,b,new l,function(b){a(b.result())},g)))};b.j(4);g.readAsText(b.b(4));return!0}}}else window.MP4={supported:!1,analyze:function(){return!1}};}());
