(function(){'use strict';var e={};function h(b){var a=/^webkit/;Object.getOwnPropertyNames(b.prototype).forEach(function(c){a.test(c)&&(b.prototype[c[6].toLowerCase()+c.slice(7)]=b.prototype[c])})}
e={s:function(){window.Blob=window.Blob||window.webkitBlob||void 0;window.File=window.File||window.webkitFile||void 0;window.FileReader=window.FileReader||window.webkitFileReader||void 0;return Blob&&File&&FileReader?(h(window.Blob),h(window.File),h(window.FileReader),!0):!1},r:function(){window.DataView=window.DataView||window.webkitDataView||void 0;return DataView?(h(window.DataView),!0):!1}};
if(e.s()&&e.r()){Blob.prototype.g=0;Blob.B=1;Blob.w=2;Blob.A=3;Blob.prototype.q=function(b){this.g+=b;this.g>this.size&&(this.g=this.size)};Blob.prototype.m=function(){return this.g===this.size};Blob.prototype.i=function(b){return this.slice(this.g,this.g+b)};Blob.prototype.v=function(b){b=this.i(b);this.g+=b.size;return b};var k=function(){this.k=this.n=this.type=null},l=function(){this.j=this.l=this.f=this.parent=null;this.result=function(){return{video:this.l&&{codec:this.l.k},audio:this.j&&{codec:this.j.k}}}},
m={64:"aac",102:"aac",103:"aac",104:"aac",105:".mp3",107:".mp3",165:"ac-3",169:"dts",221:"vorbis"},n=function(b,a){a=a||0;this.type=b.getUint8(a);this.size=0;this.b=1;this.a=0;for(var c=4;this.b++,c--;){var d=b.getUint8(a+1+(3-c));this.size=this.size<<7|d&127;if(!(d&128))break}},p=function(b,a){a=a||0;n.call(this,b,a);if(3!==this.type)this.a=this.size-this.b;else{a+=this.b;this.a=3;var c=b.getUint8(a+2);c&128&&(this.a+=2);c&64&&(this.a+=1+b.getUint8(a+this.a));c&32&&(this.a+=2)}},q=function(b,a){a=
a||0;n.call(this,b,a);4!==this.type?(this.h=null,this.a=this.size-this.b):(a+=this.b,this.h=b.getUint8(a),this.a=13)},r=function(b,a){a=a||0;this.size=b.getUint32(a,!1);this.type=String.fromCharCode.apply(null,new Uint8Array(b.buffer,a+4,4));this.b=8;this.a=0;this.parsed=!1},s={},t=function(b,a,c,d,g){a.q(b.b+b.a);a.m()?d(c):(g=g||new FileReader,g.onloadend=function(f){f.target.readyState===FileReader.DONE&&(8>f.target.result.byteLength?d(c):(f=new DataView(f.target.result),f=new r(f,0),f.size<f.b?
d(c):f.type in s&&s[f.type].e?(c.parent=b.type,s[f.type].e(f,a.v(f.size),c,function(){a.m()?d(c):g.readAsArrayBuffer(a.i(8))})):(a.q(f.size),a.m()?d(c):g.readAsArrayBuffer(a.i(8)))))},g.readAsArrayBuffer(a.i(8)))},u=function(b,a,c,d){if(b.type in s)if(b.parsed)t(b,a,c,d);else if(s[b.type].d){var g=new FileReader;g.onloadend=function(f){f.target.readyState===FileReader.DONE&&(f=new DataView(f.target.result),b=s[b.type].d(c,f,0),t(b,a,c,d,g))};g.readAsArrayBuffer(a.i(-1==s[b.type].c?b.size:s[b.type].c))}else b.a=
s[b.type].c-b.b,t(b,a,c,d);else d(c)},v=function(b,a){a=a||0;r.call(this,b,a);var c=String.fromCharCode.apply(null,new Uint8Array(b.buffer,a+12,8));this.u=c.slice(0,4);this.t=c.slice(4);this.a=this.size-this.b;this.parsed=!0},w=function(b,a){a=a||0;r.call(this,b,a);a+=12;this.o=b.getUint32(a,!1);this.p=0<this.o?String.fromCharCode.apply(null,new Uint8Array(b.buffer,a+8,4)):null;this.a=8;this.parsed=!0},x=function(b,a){a=a||0;r.call(this,b,a);this.a=16;var c=b.getUint16(a+16,!1);this.a=0===c?this.a+
12:1===c?this.a+28:2===c?this.a+48:this.size-this.b;this.parsed=!0},y=function(b,a){a=a||0;r.call(this,b,a);a+=12;this.a=this.size-this.b;var c=new p(b,a);a+=c.b+c.a;c=new q(b,a);this.h=c.h;this.parsed=!0};s.moov={e:u,c:8,d:void 0};s.trak={e:function(b,a,c,d){c.f=new k;t(b,a,c,function(a){"vide"===a.f.n&&null===a.l?a.l=a.f:"soun"===a.f.n&&null===a.j&&(a.j=a.f);a.f=null;d(a)})},c:8,d:void 0};s.mdia={e:u,c:8,d:void 0};s.hdlr={e:function(b,a,c,d){"mdia"===c.parent?u(b,a,c,d):d(c)},c:20,d:function(b,
a,c){a=new v(a,c);b.f.type=a.u;b.f.n=a.t;return a}};s.minf={e:u,c:8,d:void 0};s.stbl={e:u,c:8,d:void 0};s.stsd={e:u,c:24,d:function(b,a,c){a=new w(a,c);0<a.o&&"mp4a"!==a.p&&(b.f.k=a.p,a.a=a.size-a.b);return a}};s.mp4a={e:function(b,a,c,d){"stsd"===c.parent?u(b,a,c,d):d(c)},c:18,d:function(b,a,c){return new x(a,c)}};s.wave={e:u,c:8,d:void 0};s.esds={e:u,c:-1,d:function(b,a,c){a=new y(a,c);null!==a.h&&(b.f.k=m[a.h]);return a}};window.MP4={supported:!0,analyze:function(b,a){if(!(b instanceof Blob))throw new TypeError("Invalid argument type");
if("video/mp4"!=b.type&&"video/quicktime"!=b.type&&"audio/mp4"!=b.type)throw new TypeError("Input data format is not mp4/mov");var c=new ArrayBuffer(8),c=new DataView(c),c=new r(c);c.size=8+b.size;c.type="root";c.a=-8;c.parsed=!0;t(c,b,new l,function(b){a(b.result())});return!0}}}else window.MP4={supported:!1,analyze:function(){return!1}};}());
